### PR TITLE
perfectly vertically center OS menu buttons (OS X)

### PR DESCRIPTION
**Pull request by feross**

### CODE REVIEW

**Comment by feross** [comment]
Before:

screen shot 2016-03-06 at 12 42 26 am

After (header is 1px shorter):

screen shot 2016-03-06 at 12 42 53 am

**Comment by ngoldman** [comment]
lgtm but needs rebase after that last merge

**Comment by ngoldman** [comment]
I think I made it `38px` earlier because because the line between header and list looked better as 1px than 2px.

**Comment by feross** [comment]
Rebased and merged :)

**Pull request merged**
