### PR TITLE
Implement #116: Add Unity Launcher Shortcuts

### PR DESCRIPTION
**Pull request by grunjol**
This PR solves #116 

To implement this the following changes were made

* parameters are not longer torrentId only, handle that with processArgv function
* expose missing menu event invocation (showCreateTorrent)
* add Actions section in .desktop
* fix .desktop/register handler to be used in development mode

### CODE REVIEW

**Comment by grunjol** [comment]
@feross let me know if its too hacky

**Comment by ungoldman** [comment]
@grunjol if you cd into the project directory, switch to your working branch, then `git pull --rebase upstream master`, you will get a cleaner set of commits for a pull request (there will be no merge commits). It's generally a good idea to avoid merging the master branch on top of working branch changes.

Otherwise this PR looks good to me. :+1:

**Comment by grunjol** [comment]
You are right. In this case, its because i pushed the Update Branch button in the Pull Page when keep updating the master.

Thanks for the advice

**Comment by grunjol** [comment]
Closing to create clean branch

**Pull request closed without merging**
