### PR TITLE
Create Windows .exe installer

### PR DESCRIPTION
**Pull request by feross**
- [x] Windows: Create installer .exe file
  - [x] Loading .gif while install happens
  - [x] Install desktop/start menu shortcuts
  - [x] Installer icon
  - [x] Prevent --squirrel arguments from getting added as torrents
  - [x] Handle --squirrel arguments
  - [x] Fix install gif to not blink
- [x] [`app.setAppUserModelId`](http://electron.atom.io/docs/all/#windows)
- [x] Windows: Server-side components for updater
- [x] Build final artifacts to dist/ folder instead of inside each platform folder
- [x] Simplify arguments to `npm run package`. Now It's `npm run package -- win32`
- [x] Don't autohide top menu – it's important

### CODE REVIEW

**Comment by feross** [comment]
Moved the .exe signing out of the tasks for this PR. That can happen later.

**Comment by feross** [comment]
This is all working now! (Minus signing the .exe, which I'll do once I have a cert)

Going to do a 0.1.0 release and see how it goes :+1:

**Comment by trash-anger** [comment]
Hi !
Impressive work !
Just a very minor issue : during installation, there is no icon in the windows taskbar in the v0.3.3
capture

**Comment by rom1504** [comment]
@trash-anger yes, open a new issue

**Pull request merged**
