### PR TITLE
OS X: Add auto-updater, sign app, build .DMG and .ZIP assets

### PR DESCRIPTION
**Pull request by feross**
- Add [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) auto-updater (it's built in to electron)
  - Requires [server support](https://github.com/Squirrel/Squirrel.Mac#server-support) which I [added to `webtorrent-www`](https://github.com/feross/webtorrent-www/pull/46) (https://webtorrent.io)
- Sign app with Apple developer certificate, for two reasons:
  - Required for `Squirrel.Mac` to verify app updates are signed by the same author as the current version.
  - Allows app to run without the user needing to disable [OS X Gatekeeper](https://developer.apple.com/developer-id/).
- Signing OS X apps for distribution outside the App Store requires:
    - Xcode
    - Xcode Command Line Tools (xcode-select --install)
    - Membership in the Apple Developer Program
    - I (Feross) will sign every OS X release and ensure that the certificate is safe.
- Produce a .DMG file, for easy installs by the user (#12)
  - Here's how it looks:
  screen shot 2016-03-21 at 8 28 24 pm
- Produce a .ZIP file, which is downloaded and used by the auto-updater.

### CODE REVIEW

**Comment by ungoldman** [comment]
Looks great!

**Comment by feross** [comment]
For #190

**Comment by feross** [comment]
@ungoldman Thanks!

**Comment by feross** [comment]
The first release is available here: https://github.com/feross/webtorrent-app/releases/tag/v0.0.0

**Pull request merged**
